### ISSUE TITLE
Post-Training Data Release Timeline

### ISSUE THREAD

**Issue by alpayariyak** [OpenCoder-llm/OpenCoder-llm#1]
Thank you for the amazing work! 

When do you plan to release the post-training data?

**Comment by crazycth** [comment]
Thanks for your attention! We will make all post-train data public within 12 hours :-)

**Comment by alpayariyak** [comment]
Incredible, thank you so much @crazycth! Can't wait :)

**Comment by crazycth** [comment]
@alpayariyak Hi, we have release our 4.5M code-sft data ~
SFT Stage1: https://huggingface.co/datasets/OpenCoder-LLM/opencoder-sft-stage1
SFT Stage2: https://huggingface.co/datasets/OpenCoder-LLM/opencoder-sft-stage2

**Comment by alpayariyak** [comment]
Amazing, thank you 🤩 @crazycth

**Comment by koalazf99** [comment]
Hi, very nice work!
Similar question here: will the pre-training corpus be released?

**Comment by crazycth** [comment]
@koalazf99 Thanks for your interest! We've realized that directly open-sourcing the pretraining corpus involves some complex legal considerations. So, we’re taking a different approach to gradually open-source the pt corpus:

1. For GitHub code, we’ll release the meta info (repo name + file name) from The Stack v2 after filtering it with the OpenCoder cleaning framework. It's easy for you to collect this corpus with git clone.
2. We're working to release fully cleaned code and will provide the complete OpenCoder cleaning framework along with parameters as soon as possible.
3. For the cc portion, we’ll make the entire dataset available.

We’ll keep you updated on our progress with these steps :-)

**Comment by koalazf99** [comment]
> @koalazf99 Thanks for your interest! We've realized that directly open-sourcing the pretraining corpus involves some complex legal considerations. So, we’re taking a different approach to gradually open-source the pt corpus:
> 
> 1. For GitHub code, we’ll release the meta info (repo name + file name) from The Stack v2 after filtering it with the OpenCoder cleaning framework. It's easy for you to collect this corpus with git clone.
> 2. We're working to release fully cleaned code and will provide the complete OpenCoder cleaning framework along with parameters as soon as possible.
> 3. For the cc portion, we’ll make the entire dataset available.
> 
> We’ll keep you updated on our progress with these steps :-)

Thank you! Looking forward to it!

**Comment by alpayariyak** [comment]
Is there any chance you could release a version with a column corresponding to subset(e.g. RealUser-Instruct, etc) for both stages?

**Comment by crazycth** [comment]
@alpayariyak Hi, we've updated the classification of both stages~

**Comment by alpayariyak** [comment]
You’re the best, as always! Thank you :)
