### ISSUE TITLE
Timeline for data cleaning pipeline

### ISSUE THREAD

**Issue by Vvvvvvsysy** [OpenCoder-llm/OpenCoder-llm#11]
Great job! Thank you for sharing your work and making this repository available. I'm very interested in the data cleaning pipeline you've mentioned, and I was wondering if you have an estimated timeline for when it might be open-sourced.

**Comment by crazycth** [comment]
@Vvvvvvsysy Thank you for your attention! We've already started cleaning up this part of the code and will release it as soon as possible~
