### ISSUE TITLE
What is the requirement.txt for eval?

### ISSUE THREAD

**Issue by mst272** [OpenCoder-llm/OpenCoder-llm#12]
I am conducting bigcodebench tests, but some problems have occurred.

**Comment by SivilTaram** [comment]
@richardodliu

**Comment by jasonkleinlove** [comment]
Sorry for the missing file, we will update it and you can find it here [requirements-eval](https://github.com/bigcode-project/bigcodebench/blob/main/Requirements/requirements-eval.txt).
