### ISSUE TITLE
 cannot import name 'destroy_distributed_environment' from 'vllm.distributed.parallel_state'

### ISSUE THREAD

**Issue by mst272** [OpenCoder-llm/OpenCoder-llm#18]
When evaluating bigcodebench, the following error occurs. Have you encountered this before? Is it a problem with the vllm version?

`
Traceback (most recent call last):
  File "src/main.py", line 11, in <module>
    from backend.vllm import VllmGenerator
  File "/opt/OpenCoder-llm/OpenCodeEval/src/backend/vllm.py", line 17, in <module>
    from vllm.distributed.parallel_state import destroy_distributed_environment, destroy_model_parallel
ImportError: cannot import name 'destroy_distributed_environment' from 'vllm.distributed.parallel_state' (/home/miniconda3/envs/bigcodebench/lib/python3.8/site-packages/vllm/distributed/parallel_state.py)
`

**Comment by jasonkleinlove** [comment]
It seems like there is an error in your vllm package, and I suggest you use the latest version.

**Comment by jasonkleinlove** [comment]
It seems like there is an error in your vllm package, and I suggest you to use the latest version.
