### ISSUE TITLE
how about tokenizer training?

### ISSUE THREAD

**Issue by yucc-leon** [OpenCoder-llm/OpenCoder-llm#3]
Great works and congratulation! I noticed opencoder works with a 96K-vocab tokenizer; would your releasing include the scripts and the dataset used for training it?

**Comment by crazycth** [comment]
Our tokenizer is based on the INF-34B tokenizer, with added special tokens. Details on the training of the original INF-34B tokenizer can be found here: https://s.infly.cn/f/img/pdf/inf_34b_tech_report.pdf.

**Comment by yucc-leon** [comment]
Many thanks!
