### ISSUE TITLE
Data cleaning code opensource

### ISSUE THREAD

**Issue by GodfatherPacino** [OpenCoder-llm/OpenCoder-llm#4]
OpenCoder ensures full transparency by releasing not only the model weights and forthcoming inference code but also the complete data-cleaning code for training.
---
Great work！I have not found the data cleaning Code. Thanks if you can give some advice

**Comment by crazycth** [comment]
@GodfatherPacino Thank you for your interest! We are actively working on cleaning the code and will release the complete details of the data cleaning pipeline soon :-)

**Comment by Vvvvvvsysy** [comment]
> @GodfatherPacino Thank you for your interest! We are actively working on cleaning the code and will release the complete details of the data cleaning pipeline soon :-)

Nice job! Thank you for sharing your work and making this repository available. I'm very interested in the data cleaning pipeline you've mentioned, and I was wondering if you have an estimated timeline for when it might be open-sourced.
