### ISSUE TITLE
Inconsistent scores for humaneval

### ISSUE THREAD

**Issue by fxnie** [OpenCoder-llm/OpenCoder-llm#7]
The scores measured on the 1.5B base model are as follows

"humaneval": {
    "pass@1": 0.34146341463414637
  },
  "config": {
    "prefix": "",
    "do_sample": false,
    "temperature": 0.2,
    "top_k": 0,
    "top_p": 0.95,
    "n_samples": 1,
    "eos": "<unk>",   # is < unk >
    "seed": 0,

What parameters do I need to modify to achieve？？

**Comment by jasonkleinlove** [comment]
We report the results with the temperature = 0.0, which means the greedy decoding.
Meanwhile, we have updated the evaluation tools so that you can reproduce the results in [OpenCodeEval](https://github.com/OpenCoder-llm/OpenCoder-llm/tree/main/OpenCodeEval).

**Comment by fxnie** [comment]
If I want to perform humanEval on other models using OpenCodeEval, do I need to modify the eos or prompt in this OpenCodeEval.
The evaluation of tinyllama-v1.1 using humaneval in OpenCodeEval found that the result was very low, only 1.

**Comment by SivilTaram** [comment]
Usually there are two ways to evaluate the coding model: temperature = 0.2 with samples = 20, or temperature = 0.0 with samples = 1. You should choose the arguments carefully @fxnie
