### ISSUE TITLE
Pretraining raw dataset was scanned as unsafe by huggingface

### ISSUE THREAD

**Issue by AndyZZt** [OpenCoder-llm/OpenCoder-llm#8]
![image](https://github.com/user-attachments/assets/dfce3f7c-ca24-4216-a88f-a96b47cc0be8)

**Comment by AndyZZt** [comment]
![image](https://github.com/user-attachments/assets/8ab2d7ff-21a5-401e-b5a9-cad35a417f7f)

**Comment by yucc-leon** [comment]
It may be because some code snippets have features similar to Trojan programs. But I don't think that matters very much; you can also find the same tags on other datasets like TxT360.
